# Generated by Django 3.2.4 on 2021-06-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_urls', models.URLField(unique=True, verbose_name='URL')),
                ('short_urls', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
